export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'
export type ButtonType = 'filled' | 'outline' | 'pill' | 'link'
export type Position = 'left' | 'right' | 'none' | 'only'
export type TextSize =
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'
export type Weight = 'light' | 'normal' | 'medium' | 'semibold' | 'bold'
export type IconSize = 'xs' | 'sm' | 'md' | 'lg'
export type BadgeType =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'danger'
  | 'warning'

export type Color = 'primary' | 'secondary' | 'dark' | 'neutral'
